apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
    {{- with .Values.statefulSet.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.statefulSet.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  serviceName: {{ template "uptime-kuma.fullname" . }}
  selector:
    matchLabels:
      {{- include "uptime-kuma.selectorLabels" . | nindent 6 }}
      {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "uptime-kuma.selectorLabels" . | nindent 8 }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uptime-kuma.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "uptime-kuma.containerImage" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: UPTIME_KUMA_PORT
              value: '3001'
            - name: PORT
              value: '3001'
            {{- if .Values.extraCertificates.enabled }}
            - name: NODE_EXTRA_CA_CERTS
              value: /usr/local/share/ca-certificates/cacerts.pem
            {{- end }}
            {{- if and .Values.database (ne .Values.database.type "sqlite") }}
            - name: UPTIME_KUMA_DB_TYPE
              value: {{ .Values.database.type | quote }}
            {{- end }}
            {{- if and .Values.database (eq .Values.database.type "mariadb") }}
            {{- with .Values.database.mariadb }}
            {{- if .hostname }}
            - name: UPTIME_KUMA_DB_HOSTNAME
              value: {{ .hostname | quote }}
            {{- end }}
            {{- if .port }}
            - name: UPTIME_KUMA_DB_PORT
              value: {{ .port | quote }}
            {{- end }}
            {{- if .socket }}
            - name: UPTIME_KUMA_DB_SOCKET
              value: {{ .socket | quote }}
            {{- end }}
            {{- if .name }}
            - name: UPTIME_KUMA_DB_NAME
              value: {{ .name | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.database.existingSecret }}
            - name: UPTIME_KUMA_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: {{ .Values.database.existingSecretUsernameKey | default "username" }}
            - name: UPTIME_KUMA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: {{ .Values.database.existingSecretPasswordKey | default "password" }}
            {{- else }}
            {{- with .Values.database.mariadb }}
            {{- if .username }}
            - name: UPTIME_KUMA_DB_USERNAME
              value: {{ .username | quote }}
            {{- end }}
            {{- if .password }}
            - name: UPTIME_KUMA_DB_PASSWORD
              value: {{ .password | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- with .Values.database.mariadb }}
            {{- if .ssl }}
            - name: UPTIME_KUMA_DB_SSL
              value: "true"
            {{- end }}
            {{- if .ca }}
            - name: UPTIME_KUMA_DB_CA
              value: {{ .ca | quote }}
            {{- end }}
            {{- if and .poolMaxConnections (ne (int .poolMaxConnections) 10) }}
            - name: UPTIME_KUMA_DB_POOL_MAX_CONNECTIONS
              value: {{ .poolMaxConnections | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.statefulSet.envVars }}
            {{- toYaml .Values.statefulSet.envVars | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          volumeMounts:
            - name: uptime-storage
              mountPath: /app/data
            {{- if .Values.extraCertificates.enabled }}
            - name: cacerts
              mountPath: /usr/local/share/ca-certificates/cacerts.pem
              subPath: cacerts.pem
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: uptime-storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "uptime-kuma.persistentVolumeClaimName" . }}
          {{- else }}
          emptyDir:
            sizeLimit: 4Gi
          {{- end }}
        {{- if .Values.extraCertificates.enabled }}
        - name: cacerts
          {{- if .Values.extraCertificates.existingConfigMap }}
          configMap:
            name: {{ .Values.extraCertificates.existingConfigMap }}
            items:
              - key: {{ .Values.extraCertificates.existingConfigMapKey }}
                path: cacerts.pem
          {{- else }}
          configMap:
            name: uptime-kuma-configmap
            items:
              - key: cacerts.pem
                path: cacerts.pem
          {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
