database:
  type: "mariadb"
  mariadb:
    hostname: "mariadb.example.com"
    port: 3306
    name: "uptime-kuma"
  existingSecret: "my-db-secret"
  existingSecretUsernameKey: "db-user"
  existingSecretPasswordKey: "db-pass"
